- IBAN verification is working - New file: iban.txt: list of valid countries and valid account number length

diff --git a/hsb-members/hsb-members b/hsb-members/hsb-members
--- a/hsb-members/hsb-members
+++ b/hsb-members/hsb-members
@@ -21,7 +21,9 @@ ME=$(basename $0)
 DB="$0.csv"
 CONFIGFILE="$0.conf"
 # The raw bank statements will be stored here
-BANKHISTORY=$(dirname $0)/bank
+BANKHISTORY="$(dirname $0)/bank"
+# The IBAN database
+IBANTXT="$(dirname $0)/iban.txt"
 
 # Build the prompt array (SQL)
 # Format of the structure: SQLINPUT[number]="fieldname|field description|RESULT"
@@ -86,20 +88,28 @@ echo "+++${COMMSTR:0:3}/${COMMSTR:3:4}/${COMMSTR:7:3}$COMM_MODULO+++" # Chop int
 # Verify the IBAN account number. 
 # Input: what look like an IBAN number
 # output: a clean IBAN number with no space. Nothing if garbage.
+# Documentation: http://en.wikipedia.org/wiki/International_Bank_Account_Number
 verifyiban ()
 {
-    # Valid country prefixes with valid lengths. source: http://en.wikipedia.org/wiki/International_Bank_Account_Number
-    IBANLENGTH="AL,28|AD,24|AT,20|AZ,28|BH,22|BE,16|BA,20|BR,29|BG,22|CR,21|HR,21|CY,28|CZ,24|DK,18|DO,28|EE,20|FO,18|FI,18|FR,27"
-    IBANLENGTH="$IBANLENGTH|GE,22|DE,22|GI,23|GR,27|GL,18|GT,28|HU,28|IS,26|IE,22|IL,23|IT,27|KZ,20|KW,30|LV,21|LB,28|LI,21|LT,20"
-    IBANLENGTH="$IBANLENGTH|LU,20|MK,19|MT,31|MR,27|MU,30|MC,27|MD,24|ME,22|NL,18|NO,15|PK,24|PS,29|PL,28|PT,25|RO,24|SM,27|SA,24"
-    IBANLENGTH="$IBANLENGTH|RS,22|SK,24|SI,19|ES,24|SE,24|CH,21|TN,24|TR,26|AE,23|GB,22|VG,24"
-    IBANTABLE="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
+    # Do not remove front space: seq is 1-based, bash strings are zero-based.
+    IBANTABLE=" ABCDEFGHIJKLMNOPQRSTUVWXYZ"
     # Remove all spaces and junk from the string. They will be added later when needed.
-    IBAN=$(echo "$1"| sed -e 's/[^0-9A-Z]//gI')
+    IBAN=$(echo "$1" |tr [:lower:] [:upper:] | sed -e 's/[^0-9A-Z]//gI')
     IBANCOUNTRY=${IBAN:0:2}
     IBANMODULO=${IBAN:2:2}
     IBANACCOUNT=${IBAN:4}
-    echo "verifyiban (): IBAN is $IBAN, country is $IBANCOUNTRY, modulo is $IBANMODULO, account is $IBANACCOUNT"
+    IBANINDEX=$(matchincsv "$IBANTXT" "$IBANCOUNTRY"  1)
+    # Is it in IBAN database ?
+    if [ -n "$IBANINDEX" ]; then
+	# Is it the correct length ?
+	if [ "$(getcsvdata "$IBANTXT" $IBANINDEX 2)" -eq "$(echo -n "$IBAN" | wc -c)" ]; then
+	    # Build sed script to transform letters in numbers (A=10, B=11,... Z=35)
+	    for i in $(seq $(echo -n $IBANTABLE |wc -c)); do
+		SEDSCRIPT="s/${IBANTABLE:$i:1}/$(( $i +9 ))/gI;$SEDSCRIPT"
+	    done
+	    test $(( 10#$(echo "$IBANACCOUNT$IBANCOUNTRY$IBANMODULO" |sed -e "$SEDSCRIPT") % 97 )) -eq 1 && echo "$IBAN"
+	fi
+    fi
 }
 
 # Verify belgian-style account number. It has 12 digits separated by dashes.
@@ -318,6 +328,24 @@ else
 fi
 }
 
+# Search an exact match in the CSV file.
+# parameter 1: file name
+# parameter 2: what to search
+# parameter 3: column(s) to search into. Leave empty to search all fields
+# output: line number(s) of the matching entries (1 match per line)
+# 	  no output -> no match.
+function matchincsv()
+{
+    if [ -f "$1" ]; then
+	F="$3"
+	test -z "$F" && F='1-'
+	cat "$1"|cut -d ';' -f "$F"| grep -wn "^${2}$" | cut -d ':' -f 1
+#	die "$1 exist"
+    else
+	die "matchincsv(): File $1 doesn't exist"
+    fi
+}
+
 # Get data from CSV file
 # parameter 1: file name
 # parameter 2: row number
@@ -342,7 +370,7 @@ function getcsvdata()
 function argenta_import()
 {
     if [ -f "$1" ]; then
-	FILEHASH=$(date '+%s')-$(shasum -b $1 | cut -d ' ' -f 1)
+	FILEHASH=$(date '+%s')-$(sha1sum -b $1 | cut -d ' ' -f 1)
 	echo "$FILEHASH.csv"
 	# My bank account number is on line 1, cell 2.
 	MYACCOUNT="$(getcsvdata $1 1 2|sed -e 's/\ //g')"
@@ -386,6 +414,7 @@ BANKACCOUNT=$(echo $BANKACCOUNT|tr -d ' ')
 # If empty, use localhost
 test -n "$SQLHOST" || SQLHOST="127.0.0.1"
 mkdir -p "$BANKHISTORY" || die "Can't create csv archive directory"
+test -f "$IBANTXT" || die "Can't access file $IBANTXT"
 
 # Is the database usable ? Try listing the tables.
 SQLRESULT=$(runsql "show tables;")
